name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bots:
          - Echo
          - Moderation
    defaults:
      run:
        working-directory: ${{ matrix.bots }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ matrix.bots }}/Test/TestResults/coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ matrix.bots }}/Test/TestResults/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
